"""
Django settings for Django_Blog project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.conf.global_settings import EMAIL_BACKEND

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!bvt-!&^zj-xqpdu$9xu#8*^fximunwhv@!4z1pd6+l-e381!#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',#后台
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',#博客应用
    'mdeditor',#Markdown编辑器
    'import_export',#导入导出插件
    'corsheaders',
    'pure_pagination',
    'account',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'blog.middleware.auth.AuthMiddleware'
]

ROOT_URLCONF = 'Django_Blog.urls'
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELTST = (
    'http//:localhost:8000'
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_params',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
   'default':{
       'ENGINE':'django.db.backends.mysql',
       'NAME':'django_blog',
       'USER':'root',
       'PASSWORD':'root',
       'HOST':'127.0.0.1',
       'PORT':3306
   }
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#DATABASES = {
#   'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'django_blog',
#        'USER': 'root',
#        'PASSWORD': 'root',
#        'HOST': 'db',
#        'PORT': '3306',
#        'OPTIONS': {'charset': 'utf8mb4'},
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = False

USE_TZ = False
TIME_ZONE = 'Asia/Shanghai'  # 或你所需的时区

#日期格式
DATETIME_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "bolg/static")
#]


#SimpleUi后台设置
SIMPLEUI_LOGO = 'http://127.0.0.1:8000/media/img/img.png' #登录页和后台logo
SIMPLEUI_ANALYSIS = False #是否向SimpleUi收集分析信息
SIMPLEUI_LOADING = False #是否打开Loading遮罩层
SIMPLEUI_LOGIN_PARTICLES = True #登录页粒子动画
SIMPLEUI_STATIC_OFFLINE = True #是否以脱机模式加载静态资源，为True的时候将默认从本地读取所有资源，即使没有联网一样可以。适合内网项目，不填该项或者为False的时候，默认从第三方的cdn获取
SIMPLEUI_HOME_INFO = False #是否打开SimpleUi服务器信息
SIMPLEUI_DEFAULT_THEME = 'simpleui.css' #默认主题 https://simpleui.88cto.com/docs/simpleui/QUICK.html#%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98
SIMPLEUI_HOME_QUICK = True #后台页面是否显示最近动作
#自定义后台菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,  #去除系统模块
    'menus': [{
        'name': 'Article management',
        'icon': 'fas fa-book-open',
        'models': [{
                'name': 'Article',
                'icon': 'fas fa-book-open',
                'url': '/admin/blog/article/'
            },{
                'name': 'Classify',
                'icon': 'fas fa-list',
                'url': '/admin/blog/category/'
            },{
                'name': 'Tag',
                'icon': 'fas fa-tags',
                'url': '/admin/blog/tag/'
            },{
                'name': 'Year',
                'icon': 'fas fa-tags',
                'url': '/admin/blog/year/'
        }]
    }, {
        'name': 'Member',
        'icon': 'far fa-user',
        'url': '/admin/blog/link/'
    }, {
        'name': 'Bulletin board',
        'icon': 'fas fa-bullhorn',
        'url': '/admin/blog/notice/'
    },{
        'name': 'Settings',
        'icon': 'fas fa-address-card',
        'models': [{
            'name': 'Basic Information',
            'icon': 'far fa-file',
            'url': '/admin/blog/about/'
            },{
            'name': 'Socializing',
            'icon': 'fas fa-comment-alt',
            'url': '/admin/blog/social/'
            },{
            'name': 'Skill',
            'icon': 'fas fa-drafting-compass',
            'url': '/admin/blog/skill/'
            }]
    }, {
        'name': 'Website settings',
        'icon': 'fas fa-globe-americas',
        'url': '/admin/blog/site/'
    }, {
        'app': 'auth',
        'name': 'Users and Authorizations',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': 'User',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        },{
            'name': 'Permission groups',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        }]
    },]
}

#mdeditor设置
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/media/'   #你上传的文件和图片会默认存在/uploads/editor下
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 日志记录
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' :"[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' :"%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'mysite.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'blog': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis 的地址和数据库号
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'myapp'  # 可选，防止多个项目的缓存键冲突
    }
}




