# Generated by Django 3.2.10 on 2025-03-13 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(verbose_name='Avatar')),
                ('career', models.CharField(max_length=50, verbose_name='Career')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('skill_title', models.CharField(default='Skill', max_length=50, verbose_name='Skill Title')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category Name')),
                ('index', models.IntegerField(default=1, verbose_name='Category Order')),
                ('add_menu', models.BooleanField(default=False, verbose_name='Add to Navigation')),
                ('icon', models.CharField(default='fas fa-home', max_length=30, verbose_name='Navigation Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('avatar', models.URLField(default='https://i.loli.net/2020/04/23/jGP8gQOYW75TSJp.png', verbose_name='Avatar')),
                ('desc', models.TextField(max_length=50, verbose_name='Description')),
                ('button_word', models.CharField(default='Visit', max_length=10, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Notice Title')),
                ('content', models.TextField(max_length=500, verbose_name='Notice Content')),
                ('icon', models.CharField(default='far fa-lightbulb', max_length=50, verbose_name='Notice Icon')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SimpleSite', max_length=30, verbose_name='Site Name')),
                ('keywords', models.CharField(default='Keywords test', max_length=50, verbose_name='Keywords')),
                ('logo', models.URLField(default='/media/img/preview.jpg', max_length=100, verbose_name='Site Logo')),
                ('desc', models.CharField(max_length=50, verbose_name='Site Description')),
                ('slogan', models.CharField(max_length=50, verbose_name='Site Slogan')),
                ('dynamic_slogan', models.CharField(max_length=50, verbose_name='Dynamic Slogan')),
                ('icp_number', models.CharField(max_length=40, verbose_name='ICP Number')),
                ('icp_url', models.URLField(default='#', max_length=100, verbose_name='ICP URL')),
                ('bg_cover', models.URLField(default='/media/img/003044Cwsr1.jpg', max_length=100, verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('skill_precent', models.CharField(default='%', max_length=50, verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.URLField(verbose_name='Social URL')),
                ('social_desc', models.CharField(max_length=50, verbose_name='Description')),
                ('social_icon', models.CharField(default='fas fa-envelope', max_length=50, verbose_name='Social Icon')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('email', models.EmailField(blank=True, max_length=22, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Valine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=100, verbose_name='AppID')),
                ('appkey', models.CharField(max_length=100, verbose_name='AppKey')),
                ('avatar', models.CharField(blank=True, default='', max_length=100, verbose_name='Avatar')),
                ('pagesize', models.IntegerField(default=10, verbose_name='Page Size')),
                ('placeholder', models.CharField(max_length=100, verbose_name='Placeholder')),
            ],
            options={
                'verbose_name': 'Valine Comment',
                'verbose_name_plural': 'Valine Comment',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Year',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Article Title')),
                ('author', models.CharField(blank=True, default='Long Live the Motherland', max_length=10, null=True, verbose_name='Author')),
                ('desc', models.CharField(max_length=50, verbose_name='Article Description')),
                ('cover', models.URLField(default='https://i1.hdslb.com/bfs/article/986da61cd857a85708ef16f21ecc588e4c7edc5d.jpg@1192w.avif', verbose_name='Article Cover')),
                ('content', mdeditor.fields.MDTextField(verbose_name='Article Content')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Reading Count')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='Recommended')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Publish Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Article Category')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Article Tag')),
                ('years', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.year', verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'ordering': ('-add_time',),
            },
        ),
    ]
